#!/bin/bash

# Export Groth16 verifier contract from circuit
echo "Exporting Groth16 verifier from circuit..."

cd circuits/compiled

# Export verifier using snarkjs
npx snarkjs zkey export solidityverifier verify_nonmembership_0000.zkey ../../contracts/src/Groth16Verifier.sol

echo "✅ Verifier exported to contracts/src/Groth16Verifier.sol"

# Update contract name and version
cd ../../contracts/src
sed -i 's/contract Verifier/contract Groth16Verifier/g' Groth16Verifier.sol
sed -i '1s/^/\/\/ SPDX-License-Identifier: GPL-3.0\n\/\/ Generated by snarkjs\npragma solidity ^0.8.24;\n\n/' Groth16Verifier.sol

echo "✅ Verifier contract updated"
